/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-10-21 05:06:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.profile;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class resumeForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1580293303682L));
    _jspx_dependants.put("jar:file:/C:/Users/geekh/Desktop/jrcp_workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SpringProject_JobRecipe/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>잡레시피</title>\r\n");
      out.write("<link type=\"text/css\" href=\"/resources/css/jobCSS.css\" rel=\"stylesheet\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/resources/js/jobJS.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/jquery-3.1.1.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("textarea.flexible {\r\n");
      out.write("\tmin-width: 200px;\r\n");
      out.write("\tmin-height: 50px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t//textarea 자동 크기 조절\r\n");
      out.write("\t\t$(\"textarea.flexible\").on('keydown keyup', function() {\r\n");
      out.write("\t\t  $(this).height(1).height( $(this).prop('scrollHeight')+12 );\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tvar upload = document.querySelector('#upload');\r\n");
      out.write("\t    var preview = document.querySelector('#preview');\r\n");
      out.write("\t \r\n");
      out.write("\t    upload.addEventListener('change',function (e) {\r\n");
      out.write("\t        var get_file = e.target.files;\r\n");
      out.write("\r\n");
      out.write("\t        var image = document.createElement('img');\r\n");
      out.write("\t        image.id = 'prev_img';\r\n");
      out.write("\t        /* FileReader 객체 생성 */\r\n");
      out.write("\t        var reader = new FileReader();\r\n");
      out.write("\t \r\n");
      out.write("\t        /* reader 시작시 함수 구현 */\r\n");
      out.write("\t        reader.onload = (function (aImg) {\r\n");
      out.write("\t            console.log(1);\r\n");
      out.write("\t \r\n");
      out.write("\t            return function (e) {\r\n");
      out.write("\t                console.log(3);\r\n");
      out.write("\t                /* base64 인코딩 된 스트링 데이터 */\r\n");
      out.write("\t                aImg.src = e.target.result\r\n");
      out.write("\t            }\r\n");
      out.write("\t        })(image)\r\n");
      out.write("\t \r\n");
      out.write("\t        if(get_file){\r\n");
      out.write("\t            /* \r\n");
      out.write("\t                get_file[0] 을 읽어서 read 행위가 종료되면 loadend 이벤트가 트리거 되고 \r\n");
      out.write("\t                onload 에 설정했던 return 으로 넘어간다.\r\n");
      out.write("\t                이와 함게 base64 인코딩 된 스트링 데이터가 result 속성에 담겨진다.\r\n");
      out.write("\t            */\r\n");
      out.write("\t            reader.readAsDataURL(get_file[0]);\r\n");
      out.write("\t            console.log(2);\r\n");
      out.write("\t        }\r\n");
      out.write("\t \t\t$(\"#preview\").empty();\r\n");
      out.write("\t        preview.appendChild(image);\r\n");
      out.write("\t        $(\"#prev_img\").css(\"height\", \"20vh\");\r\n");
      out.write("\t    });\r\n");
      out.write("\t    \r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("/* Noto Sans KR 폰트 추가 */\r\n");
      out.write("@import url(http://fonts.googleapis.com/earlyaccess/notosanskr.css);\r\n");
      out.write("body {\r\n");
      out.write("\tfont-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input, textarea {\r\n");
      out.write("\tfont-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("\tfont-size: initial;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/header.jsp", out, false);
      out.write("\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<section>\r\n");
      out.write("\t\t<!-- 전체 화면 -->\r\n");
      out.write("\t\t<div style=\"width: 100%; display: flex; flex-wrap: nowrap; min-height: 70vh;\">\r\n");
      out.write("\t\t\t<div style=\"width: 15%; margin-left: 3%;\">\r\n");
      out.write("\t\t\t\t<div id=\"myPageMenu\">\r\n");
      out.write("\t\t\t\t\t<div class=\"mypagemenu_wrap\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"display: flex; flex-direction: column; flex-wrap: nowrap; text-align: center\">\r\n");
      out.write("\t\t\t\t\t\t\t<div onclick=\"location.href='settings.do'\" style=\"padding:1%;font-size:18pt;cursor:pointer;margin-bottom:3%;\r\n");
      out.write("\t\t\t\t\t\t\t\tborder:1px solid #fac5a1;color:#ff6900;border-radius:10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t계정\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div onclick=\"location.href='resumes.do'\" style=\"padding:1%;font-size:18pt;cursor:pointer;margin-bottom:3%;\r\n");
      out.write("\t\t\t\t\t\t\t\tborder:1px solid #fac5a1;color:#ff6900;border-radius:10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t프로필\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div onclick=\"location.href='reviews.do'\" style=\"padding:1%;font-size:18pt;cursor:pointer;margin-bottom:3%;\r\n");
      out.write("\t\t\t\t\t\t\t\tborder:1px solid #fac5a1;color:#ff6900;border-radius:10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t내 리뷰\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div style=\"width: 60%; display: flex; flex-direction: column; margin-bottom: 5%; margin-left: 5%\" id=\"rsm_contents_wrap\">\r\n");
      out.write("\t\t\t\t<form action=\"insertResume.do\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t\t\t<div id=\"rsm_contents\">\r\n");
      out.write("\t\t\t\t\t\t<!-- 기본 정보 섹션 -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"section_wrap\" style=\"padding:3%;margin-bottom:5%;margin-right:auto; margin-left:auto;border:1px solid #fafafa;background-color:#fafafa;\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 각 입력 내용 섹션 분류용 래퍼 -->\r\n");
      out.write("\t\t\t\t\t\t\t<h2 style=\"font-size: 16pt; font-weight: 900; margin-bottom: 5%;\">기본정보</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"pro_no\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profileVO.pro_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"resume_title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"이력서의 제목을 입력해주세요.\" name=\"res_title\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${res_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"width: 50%; border: 1px solid #ff6900; border-radius: 10px; padding: 1%; margin-bottom: 3%;\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"gender_radio rsm_half_cell\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- rsm_half_cell : 가로 기준 섹션 셀의 반을 차지 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"gender_header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3\tstyle=\"font-size: 13pt; font-weight: 600; margin-bottom: 3%;\">성별</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"btn_radio\" for=\"gender_man\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"pro_gender\" id=\"gender_man\" value=\"1\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profileVO.pro_gender eq 1 ? \"checked\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"radio_txt\">남자</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"btn_radio\" for=\"gender_woman\"\tstyle=\"margin-left: 15%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"radio\"\tname=\"pro_gender\" id=\"gender_woman\" value=\"2\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profileVO.pro_gender eq 2 ? \"checked\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"radio_txt\">여자</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"birth_wrap rsm_half_cell\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"birth_header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3\tstyle=\"font-size: 13pt; font-weight: 600; margin-bottom: 3%; margin-top: 3%;\">출생연도</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"birthYear_select\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select id=\"birth_year\" name=\"pro_birthYear\" style=\"width: 15%; border: 1px solid #ff6900; border-radius: 10px; padding: 1%; margin-bottom: 3%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"none\">선택해주세요.</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2006\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profileVO.pro_birthYear eq 2006 ? \"selected\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">2006년</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2005\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profileVO.pro_birthYear eq 2005 ? \"selected\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profileVO.pro_gender eq 2006 ? \"selected\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">2005년</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2004\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profileVO.pro_birthYear eq 2004 ? \"selected\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">2004년</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2003\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profileVO.pro_birthYear eq 2003 ? \"selected\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">2003년</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2002\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profileVO.pro_birthYear eq 2002 ? \"selected\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">2002년</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2001\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profileVO.pro_birthYear eq 2001 ? \"selected\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">2001년</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2000\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profileVO.pro_birthYear eq 2000 ? \"selected\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">2000년</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1999\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profileVO.pro_birthYear eq 1999 ? \"selected\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">1999년</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1998\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profileVO.pro_birthYear eq 1998 ? \"selected\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">1998년</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1997\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profileVO.pro_birthYear eq 1997 ? \"selected\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">1997년</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1996\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profileVO.pro_birthYear eq 1996 ? \"selected\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">1996년</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1995\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profileVO.pro_birthYear eq 1995 ? \"selected\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">1995년</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1994\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profileVO.pro_birthYear eq 1994 ? \"selected\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">1994년</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1993\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profileVO.pro_birthYear eq 1993 ? \"selected\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">1993년</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1992\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profileVO.pro_birthYear eq 1992 ? \"selected\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">1992년</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1991\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profileVO.pro_birthYear eq 1991 ? \"selected\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">1991년</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1990\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profileVO.pro_birthYear eq 1990 ? \"selected\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">1990년</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"occu_wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 관심 직종 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"occu_header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 style=\"font-size: 13pt; font-weight: 600; margin-bottom: 3%; margin-top: 3%;\">현재(관심)직종</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"select\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select id=\"occu_content\" name=\"pro_occu\" style=\"width: 15%; border: 1px solid #ff6900; border-radius: 10px; padding: 1%; margin-bottom: 3%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"none\">선택해주세요.</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"IT/인터넷\">IT/인터넷</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select id=\"subOccu_content\" name=\"pro_subOccu\"\tstyle=\"width: 15%; border: 1px solid #ff6900; border-radius: 10px; padding: 1%; margin-bottom: 3%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"none\">선택해주세요.</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"JAVA\">JAVA</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"데이터베이스\">데이터베이스</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"네트워크\">네트워크</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"보안\">보안</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"career_wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"career_header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3\tstyle=\"font-size: 13pt; font-weight: 600; margin-bottom: 3%; margin-top: 3%;\">총\t경력</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"career_select\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select id=\"career\" name=\"pro_career\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 15%; border: 1px solid #ff6900; border-radius: 10px; padding: 1%; margin-bottom: 3%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"none\">선택해주세요.</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"0\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profileVO.pro_career eq 0 ? \"selected\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">0</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profileVO.pro_career eq 1 ? \"selected\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">1</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profileVO.pro_career eq 2 ? \"selected\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">2</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"3\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profileVO.pro_career eq 3 ? \"selected\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">3</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"4\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profileVO.pro_career eq 4 ? \"selected\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">4</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"5\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profileVO.pro_career eq 5 ? \"selected\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">5</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"6\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profileVO.pro_career eq 6 ? \"selected\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">6</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"7\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profileVO.pro_career eq 7 ? \"selected\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">7</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"8\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profileVO.pro_career eq 8 ? \"selected\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">8</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"9\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profileVO.pro_career eq 9 ? \"selected\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">9</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"10\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profileVO.pro_career eq 10 ? \"selected\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">10</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"skill_wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"skill_header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 style=\"font-size: 13pt; font-weight: 600; margin-bottom: 3%; margin-top: 3%;\">업무 및 스킬</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"skill_content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"pro_skill\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplaceholder=\"(예시) java, python, 서버 구축 (업무와 관련된 자격증 및 기술명  포함)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 65%; border: 1px solid #ff6900; border-radius: 10px; padding: 1%; margin-bottom: 3%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"profile_wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"profile1_header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"font-size: 13pt; font-weight: 600; margin-bottom: 3%; margin-top: 3%;\">이름,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t연락처(필수)</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"proflie1_content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"profile_input\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"set1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- set1 옆에 프로필 이미지가 라벨 형식으로 붙음 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"input_name\" name=\"pro_name\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"이름\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 15%; border: 1px solid #ff6900; border-radius: 10px; padding: 1%; margin-bottom: 1%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"set2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"input_email\" name=\"pro_email\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"이메일\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 30%; border: 1px solid #ff6900; border-radius: 10px; padding: 1%; margin-bottom: 1%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"set2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"input_tel\" name=\"pro_tel\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"전화번호\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 20%; border: 1px solid #ff6900; border-radius: 10px; padding: 1%; margin-bottom: 1%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"resume_addPhoto\" for=\"resume_addPhoto_id\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"file\" id=\"upload\" name=\"pro_imgFile\" style=\"width: 80%;\" onclick=\"changeImg();\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span id='preview'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t이미지를 선택해주세요.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"profile2_header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"font-size: 13pt; font-weight: 600; margin-bottom: 3%; margin-top: 3%;\">자기소개</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"profile2_content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"flexible_textarea\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- class 통해서 텍스트에어리어 크기 조절 필요 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<textarea class=\"flexible\" name=\"pro_aboutMe\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"경력, 경험 위주의 자기소개를 작성해주세요. 관심분야, 앞으로의 목표등의 내용도 좋습니다.\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 90%; border: 1px solid #ff6900; border-radius: 10px; padding: 1%; margin-bottom: 3%;\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- 학력, 경력, 활동 수상 내역, 포트폴리오 등등 입력 섹션 -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"section_wrap\" style=\"padding:3%;margin-bottom:5%;margin-right:auto; margin-left:auto;border:1px solid #fafafa;background-color:#fafafa;\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 학력사항 -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"education_header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3 style=\"font-size: 13pt; font-weight: 600; margin-bottom: 3%; margin-top: 3%;\">학력사항</h3>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"flexible_resume\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"left_resume_flexible\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"group_date\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- <div class=\"month_picker\"> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"e_edate\" placeholder=\"년/월\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 20%; border: 1px solid #ff6900; border-radius: 10px; padding: 1%; margin-bottom: 0%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- </div> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"resume_etc\">~</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- <div class=\"month_picker\"> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"e_gdate\" placeholder=\"년/월\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 20%; border: 1px solid #ff6900; border-radius: 10px; padding: 1%; margin-bottom: 1%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- </div> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"group_check\" style=\"margin-bottom: 1%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"btn_check\"> <!-- 체크박스 클릭시 value 변경해주는 javascript 로직 필요 / 아래도 동일 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input id=\"e_attendcheck\" name=\"e_attendcheck\" type=\"checkbox\" onclick=\"users_changeCkboxVal('e_attendcheck');\" value=\"0\" style=\"\"> <!-- <span class=\"check_icon\"></span> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"check_txt\">재학중</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"right_resume_flexible\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"sname\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input placeholder=\"학교명\" type=\"text\" name=\"e_sname\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 30%; border: 1px solid #ff6900; border-radius: 10px; padding: 1%; margin-bottom: 1%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"majordegree\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input placeholder=\"전공 및 학위\" type=\"text\" name=\"e_majordegree\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 30%; border: 1px solid #ff6900; border-radius: 10px; padding: 1%; margin-bottom: 1%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"flexible_textarea\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- class 통해서 텍스트에어리어 크기 조절 필요 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<textarea class=\"flexible\" name=\"e_description\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"학력사항에 추가로 기재할 특별한 사항이 있을 경우 입력하세요. 추가로 기재할 사항이 없을 경우 입력하지 않으셔도 괜찮습니다.\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 90%; border: 1px solid #ff6900; border-radius: 10px; padding: 1%; margin-bottom: 3%;\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 경력사항 -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"career_header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"font-size: 13pt; font-weight: 600; margin-bottom: 3%; margin-top: 3%;\">경력사항</h3>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"flexible_resume\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"left_resume_flexible\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"group_date\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- <div class=\"month_picker\"> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"car_edate\" placeholder=\"년/월\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 20%; border: 1px solid #ff6900; border-radius: 10px; padding: 1%; margin-bottom: 1%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- </div> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"resume_etc\">~</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- <div class=\"month_picker\"> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"car_rdate\" placeholder=\"년/월\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 20%; border: 1px solid #ff6900; border-radius: 10px; padding: 1%; margin-bottom: 0%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- </div> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"group_check\" style=\"margin-bottom: 1%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"btn_check\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input id=\"car_inoffice\" name=\"car_inoffice\" type=\"checkbox\" onclick=\"users_changeCkboxVal('car_inoffice');\" value=\"0\"> <!-- <span class=\"check_icon\"></span> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"check_txt\" style=\"margin-bottom: 1%;\">재직중</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"right_resume_flexible\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"sname\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input placeholder=\"기업명\" type=\"text\" name=\"car_cname\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 30%; border: 1px solid #ff6900; border-radius: 10px; padding: 1%; margin-bottom: 1%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"depart_post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input placeholder=\"부서\" type=\"text\" name=\"car_department\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 20%; border: 1px solid #ff6900; border-radius: 10px; padding: 1%; margin-bottom: 1%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"rsm_dash\">/</span> <input placeholder=\"직책\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" name=\"car_position\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 20%; border: 1px solid #ff6900; border-radius: 10px; padding: 1%; margin-bottom: 0%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"duty\" style=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input placeholder=\"직무\" type=\"text\" name=\"car_duty\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 30%; border: 1px solid #ff6900; border-radius: 10px; padding: 1%; margin-bottom: 1%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"flexible_textarea\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- class 통해서 텍스트에어리어 크기 조절 필요 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<textarea class=\"flexible\" name=\"car_workexp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"업무경험을 입력하세요. 추상적인 내용보다는 수치가 들어간 간결하고 객관적인 내용을 입력하는 것이 좋습니다. 예) 미디어 사업부(연간 매출 약 10억, 회원 50만 증가)의 사업전략 수립, 신규 사업 도입으로 3년간 내년 매출 약 2배 상승 기여\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 90%; border: 1px solid #ff6900; border-radius: 10px; padding: 1%; margin-bottom: 3%;\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 활동 및 수상내역 -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"actAwards_header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"font-size: 13pt; font-weight: 600; margin-bottom: 3%; margin-top: 3%;\">활동\r\n");
      out.write("\t\t\t\t\t\t\t\t\t및 수상내역</h3>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"flexible_resume\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"left_resume_flexible\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"group_date\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- <div class=\"month_picker\"> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"act_sdate\" placeholder=\"년/월\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 20%; border: 1px solid #ff6900; border-radius: 10px; padding: 1%; margin-bottom: 1%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- </div> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"resume_etc\">~</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- <div class=\"month_picker\"> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"act_edate\" placeholder=\"년/월\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 20%; border: 1px solid #ff6900; border-radius: 10px; padding: 1%; margin-bottom: 1%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- </div> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"group_check\" style=\"margin-bottom: 1%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"btn_check\"> <!-- 체크박스 클릭시 value 변경해주는 javascript 로직 필요 / 아래도 동일 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input id=\"act_awardCheck\" name=\"act_awardCheck\" type=\"checkbox\" onclick=\"users_changeCkboxVal('act_awardCheck');\" value=\"0\"> <!-- <span class=\"check_icon\"></span> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"check_txt\">수상</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"right_resume_flexible\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"actAwardname\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input placeholder=\"활동 및 수상명을 작성합니다.\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"act_actawardname\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 45%; border: 1px solid #ff6900; border-radius: 10px; padding: 1%; margin-bottom: 1%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"flexible_textarea\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<textarea class=\"flexible\" name=\"act_description\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"활동 및 수상과 관련한 상세한 정보가 필요한 경우 입력하세요. 추가로 기재할 사항이 없을 경우 입력하지 않으셔도 괜찮습니다.\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 90%; border: 1px solid #ff6900; border-radius: 10px; padding: 1%; margin-bottom: 3%;\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 자격증 및 기타 -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"certiOthers_header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"font-size: 13pt; font-weight: 600; margin-bottom: 3%; margin-top: 3%;\">자격증\r\n");
      out.write("\t\t\t\t\t\t\t\t\t및 기타</h3>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"certiOthers_body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"certiOhtersName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input placeholder=\"항목(자격증, 언어, 스킬 등 자유롭게 기재)\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"cer_item\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 45%; border: 1px solid #ff6900; border-radius: 10px; padding: 1%; margin-bottom: 1%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"flexible_textarea\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea class=\"flexible\" name=\"cer_description\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplaceholder=\"항목에 해당하는 상세 내용을 입력하세요. 예) 토익/780점\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 90%; border: 1px solid #ff6900; border-radius: 10px; padding: 1%; margin-bottom: 3%;\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 포트폴리오 파일 첨부 -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"portfolios_header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3 style=\"font-size: 13pt; font-weight: 600; margin-bottom: 3%; margin-top: 3%;\">포트폴리오 파일 첨부</h3>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"portfolio_body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"label_upload_resume\"> <input type=\"file\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"input_upload_resume\" name=\"por_file\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"btn_upload_resume\">파일선택</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- section_wrap-end -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<hr style=\"margin-bottom:1%; border:solid 1px #fac5a1\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"resume_btn_complete\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" style=\"font-size: 12pt;font-weight: 600;background-color:#ff6900;width: 12%;color:white;border:0;border-radius:10px;margin-left: 85%;padding: 1%;\">작성완료</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t&gt;\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t</footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
