/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-10-20 10:16:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.hire;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class InsertReviewForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1596614775737L));
    _jspx_dependants.put("jar:file:/D:/Java_Web_PM_Class_JB/project/jrcp_workspace10-20/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SpringProject_JobRecipe/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>리뷰 추가</title>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("<style>\r\n");
      out.write("\t.star1 {\r\n");
      out.write("\t    background: url('/resources/images/star_on.png') no-repeat 0 0;\r\n");
      out.write("\t    background-size: auto 100%;\r\n");
      out.write("\t    width: 15px;\r\n");
      out.write("\t    height: 30px;\r\n");
      out.write("\t    float:left;\r\n");
      out.write("\t    cursor: pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\t.star2 {\r\n");
      out.write("\t    background: url('/resources/images/star_on.png') no-repeat right 0;\r\n");
      out.write("\t    background-size: auto 100%;\r\n");
      out.write("\t    width: 15px;\r\n");
      out.write("\t    height: 30px;\r\n");
      out.write("\t    float:left;\r\n");
      out.write("\t    cursor: pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\t.star1.on {background-image: url('/resources/images/star.png');}\r\n");
      out.write("\t.star2.on {background-image: url('/resources/images/star.png');}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar review_title = 0;\r\n");
      out.write("\tvar review_advan = 0;\r\n");
      out.write("\tvar review_weak = 0;\r\n");
      out.write("\tvar review_wish = 0;\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$('.review_star span').click(function() { //평점\r\n");
      out.write("\t\t\t$(this).parent().children('span').removeClass('on');\r\n");
      out.write("\t\t\t$(this).addClass('on').prevAll('span').addClass('on');\r\n");
      out.write("\t\t\t$(\"#rev_star\").val($(this).attr(\"id\"));\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#rev_title\").keyup(function() {\r\n");
      out.write("\t\t\tvar content = $(this).val();\r\n");
      out.write("\t\t\tif(content.length > 30) {\r\n");
      out.write("\t\t\t\t$(\"#titleText\").css(\"color\", \"green\");\r\n");
      out.write("\t\t\t\treview_title = 1;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$(\"#titleText\").css(\"color\", \"red\");\r\n");
      out.write("\t\t\t\treview_title = 0;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#rev_advan\").keyup(function() {\r\n");
      out.write("\t\t\tvar content = $(this).val();\r\n");
      out.write("\t\t\tif(content.length > 30) {\r\n");
      out.write("\t\t\t\t$(\"#advanText\").css(\"color\", \"green\");\r\n");
      out.write("\t\t\t\treview_advan = 1;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$(\"#advanText\").css(\"color\", \"red\");\r\n");
      out.write("\t\t\t\treview_advan = 0;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#rev_weak\").keyup(function() {\r\n");
      out.write("\t\t\tvar content = $(this).val();\r\n");
      out.write("\t\t\tif(content.length > 30) {\r\n");
      out.write("\t\t\t\t$(\"#weakText\").css(\"color\", \"green\");\r\n");
      out.write("\t\t\t\treview_weak = 1;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$(\"#weakText\").css(\"color\", \"red\");\r\n");
      out.write("\t\t\t\treview_weak = 0;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#rev_wish\").keyup(function() {\r\n");
      out.write("\t\t\tvar content = $(this).val();\r\n");
      out.write("\t\t\tif(content.length > 30) {\r\n");
      out.write("\t\t\t\t$(\"#wishText\").css(\"color\", \"green\");\r\n");
      out.write("\t\t\t\treview_wish = 1;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$(\"#wishText\").css(\"color\", \"red\");\r\n");
      out.write("\t\t\t\treview_wish = 0;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tfunction insert_Review_Check() {\r\n");
      out.write("\t\tif($('input:radio[name=\"rev_state\"]').is(':checked') == false) {\r\n");
      out.write("\t\t\talert(\"직장 여부를 체크하세요.\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else if($('input:radio[name=\"rev_emp\"]').is(':checked') == false) {\r\n");
      out.write("\t\t\talert(\"고용형태를 체크하세요.\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else if(review_title == 0) {\r\n");
      out.write("\t\t\talert(\"30자 이상 기재해 주세요.\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else if(review_advan == 0) {\r\n");
      out.write("\t\t\talert(\"30자 이상 기재해 주세요.\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else if(review_weak == 0) {\r\n");
      out.write("\t\t\talert(\"30자 이상 기재해 주세요.\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else if(review_wish == 0) {\r\n");
      out.write("\t\t\talert(\"30자 이상 기재해 주세요.\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<body style=\"margin:0;\">\r\n");
      out.write("\t\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/header.jsp", out, false);
      out.write("\r\n");
      out.write("\t</header>\r\n");
      out.write("\t\r\n");
      out.write("\t<section>\r\n");
      out.write("\t\t<div style=\"width: 100%; display: flex; flex-wrap: nowrap; min-height: 70vh;\">\r\n");
      out.write("\t\t<!-- 전체화면 -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div style=\"width: 15%;\t margin-left: 3%;\">\r\n");
      out.write("\t\t\t<!--  left -->\r\n");
      out.write("\t\t\t\t<!-- <div style=\"display:flex; flex-direction: column; border\">\r\n");
      out.write("\t\t\t\t\t<img style=\"height:17vh;\" src=\"/resources/images/default_user.png\">\r\n");
      out.write("\t\t\t\t\t<div>이름</div>\r\n");
      out.write("\t\t\t\t\t<div>아이디</div>\r\n");
      out.write("\t\t\t\t\t<div>...</div>\r\n");
      out.write("\t\t\t\t\t<div>...</div>\r\n");
      out.write("\t\t\t\t\t<div>...</div>\r\n");
      out.write("\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div style=\"width: 60%;display:flex; flex-direction: column;margin-bottom:5%; \">\r\n");
      out.write("\t\t\t\t<!--center  -->\r\n");
      out.write("\t\t\t\t<div style=\"width:100%;text-align:center;margin-top:5%;margin-bottom:3%;color:#ff6900;\">\r\n");
      out.write("\t\t\t\t\t<h1 >");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rev_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" Review 등록</h1>\r\n");
      out.write("\t\t\t\t\t<hr style=\"border:solid 1px #fac5a1\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!--//////////////////////////////////  -->\r\n");
      out.write("\t\t\t\t\t<form action=\"insertReview.do\"\r\n");
      out.write("\t\t\t\t\t\tonsubmit=\"return insert_Review_Check()\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"rev_name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rev_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"width: 85%;display:flex;flex-direction: column;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"display:flex;flex-direction: row;flex-wrap: nowrap;margin-bottom:2%;\r\n");
      out.write("\t\t\t\t\t\t\t\tpadding-left:4%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"padding-left:4%;width:35%;font-weight:bold;\">현직장/전직장</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label style=\"width:20%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"rev_state\" value=\"현직장\">현직장\r\n");
      out.write("\t\t\t\t\t\t\t\t</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t<label style=\"width:20%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"rev_state\" value=\"전직장\">전직장\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"display:flex;flex-direction: row;flex-wrap: nowrap;\r\n");
      out.write("\t\t\t\t\t\t\t\tmargin-bottom:2%;padding-left:4%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"padding-left:4%;width:35%;font-weight:bold;\">직무</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"checkJob\" name=\"rev_job\" required=\"required\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t placeholder=\"찾기\" onclick=\"review_checkJob()\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"button\" id=\"modalBtn\" value=\"찾기\" data-toggle=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-target=\"#myModal\" style=\"margin-left:1%;background-color:#fac5a1;\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcolor:white;border:0;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"modal fade\" id=\"myModal\" role=\"dialog\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<b>직무 선택</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<span>&times;</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"job\" value=\"QA\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tQA\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp; \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"job\" value=\"프로젝트매니저\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t프로젝트매니저\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<br> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"job\" value=\"모바일앱개발\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t모바일앱개발\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp; \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"job\" value=\"웹개발\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t웹개발\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<br> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"job\" value=\"DBA\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tDBA\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp; \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"job\" value=\"시스템엔지니어\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t시스템엔지니어\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<br> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"job\" value=\"소프트웨어엔지니어\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t소프트웨어엔지니어\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp; \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"job\" value=\"하드웨어엔지니어\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t하드웨어엔지니어\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<br> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"job\" value=\"네트워크/보안/운영\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t네트워크/보안/운영\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp; \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"job\" value=\"게임개발\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t게임개발\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<br> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"button\" value=\"선택\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tonclick=\"review_job_check()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"display:flex;flex-direction: row;flex-wrap: nowrap;\r\n");
      out.write("\t\t\t\t\t\t\t\tmargin-bottom:2%;padding-left:4%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"padding-left:4%;width:35%;font-weight:bold;\">고용형태</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label style=\"width:15%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"rev_emp\" value=\"정규직\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t정규직\r\n");
      out.write("\t\t\t\t\t\t\t\t</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t<label style=\"width:15%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"rev_emp\" value=\"계약직\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t계약직\r\n");
      out.write("\t\t\t\t\t\t\t\t</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t<label style=\"width:15%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"rev_emp\" value=\"인턴\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t인턴\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"font-style:italic;font-size:9pt;padding-left:5%;margin-bottom:5%;\">\r\n");
      out.write("\t\t\t\t\t\t\t* 경력 정보는 노출되지 않습니다. (현재, 또는 퇴직 당시의 경력 정보를 입력해 주세요.)\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"display:flex;flex-direction: row;flex-wrap: nowrap;\r\n");
      out.write("\t\t\t\t\t\t\t\tmargin-bottom:3%;padding-left:4%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"padding-left:4%;width:35%;font-weight:bold;\">기업 총 평가</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"review_star\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"star1 on\" id=\"0.5\"></span> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"star2\" id=\"1.0\"></span> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"star1\" id=\"1.5\"></span> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"star2\" id=\"2.0\"></span> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"star1\" id=\"2.5\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"star2\" id=\"3.0\"></span> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"star1\" id=\"3.5\"></span> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"star2\" id=\"4.0\"></span> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"star1\" id=\"4.5\"></span> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"star2\" id=\"5.0\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"rev_star\" name=\"rev_star\" value=\"0.5\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"display:flex;flex-direction: row;flex-wrap: nowrap;\r\n");
      out.write("\t\t\t\t\t\t\t\tmargin-bottom:3%;padding-left:4%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"padding-left:4%;width:35%;font-weight:bold;padding-top: 3%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t기업 한줄 평\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<textarea name=\"rev_title\" id=\"rev_title\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\trequired=\"required\" cols=\"40\" rows=\"2\" style=\"resize: none;width:45%;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplaceholder=\"최소 30자 이상 기재해 주세요.\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"width:15%;font-size:12pt;padding-top:3%;margin-left:3%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t최소 30자\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span id=\"titleText\" style=\"padding-top: 3%;color: red;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<b>√</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"display:flex;flex-direction: row;flex-wrap: nowrap;\r\n");
      out.write("\t\t\t\t\t\t\t\tmargin-bottom:3%;padding-left:4%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"padding-left:4%;width:35%;font-weight:bold;padding-top: 3%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t기업의 장점\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<textarea name=\"rev_advan\" id=\"rev_advan\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\trequired=\"required\" cols=\"40\" rows=\"5\" style=\"resize: none;width:45%;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplaceholder=\"최소 30자 이상 기재해 주세요.\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"width:15%;font-size:12pt;padding-top:3%;margin-left:3%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t최소 30자\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span id=\"advanText\" style=\"padding-top: 3%;color: red;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<b>√</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"display:flex;flex-direction: row;flex-wrap: nowrap;\r\n");
      out.write("\t\t\t\t\t\t\t\tmargin-bottom:3%;padding-left:4%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"padding-left:4%;width:35%;font-weight:bold;padding-top: 3%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t기업의 단점\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<textarea name=\"rev_weak\" id=\"rev_weak\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\trequired=\"required\" cols=\"40\" rows=\"2\" style=\"resize: none;width:45%;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplaceholder=\"최소 30자 이상 기재해 주세요.\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"width:15%;font-size:12pt;padding-top:3%;margin-left:3%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t최소 30자\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span id=\"weakText\" style=\"padding-top: 3%;color: red;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<b>√</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"display:flex;flex-direction: row;flex-wrap: nowrap;\r\n");
      out.write("\t\t\t\t\t\t\t\tmargin-bottom:3%;padding-left:4%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"padding-left:4%;width:35%;font-weight:bold;padding-top: 3%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t경영진에게 바라는 점\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<textarea name=\"rev_wish\" id=\"rev_wish\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\trequired=\"required\" cols=\"40\" rows=\"2\" style=\"resize: none;width:45%;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplaceholder=\"최소 30자 이상 기재해 주세요.\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"width:15%;font-size:12pt;padding-top:3%;margin-left:3%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t최소 30자\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span id=\"wishText\" style=\"padding-top: 3%;color: red;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<b>√</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"width:100%;text-align:end;margin-top:5%;margin-bottom:3%;\">\r\n");
      out.write("\t\t\t\t\t\t\t<input style=\"width:20%;border:0;background-color:#ff6900;color:white;\r\n");
      out.write("\t\t\t\t\t\t\t\tfont-size:20pt;margin-right:18%;\" type=\"submit\" value=\"추가\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<!--//////////////////////////////////  -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"width: 25%; align-items:center;display:flex; flex-direction: column;\">\r\n");
      out.write("\t\t\t<!--분할화면 오른쪽  -->\r\n");
      out.write("\t\t\t\t<div style=\"margin-bottom:3%;margin-top:6%; align-items:center;display:flex; flex-direction: column;\">\r\n");
      out.write("\t\t\t\t\t<img style=\"border-radius: 30px;width:90%;\" src=\"/resources/images/ad1.gif\"/>\r\n");
      out.write("\t\t\t\t\t<div style=\"margin-top:2%; font-size:20pt; font-weight:bold;font-style: italic;\">Kaja Airline</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div style=\"margin-bottom:3%; align-items:center;display:flex; flex-direction: column;\">\r\n");
      out.write("\t\t\t\t\t<img style=\"border-radius: 30px;width:90%;\" src=\"/resources/images/ad2.gif\"/>\r\n");
      out.write("\t\t\t\t\t<div style=\"margin-top:2%; font-size:20pt; font-weight:bold;font-style: italic;\">Kaja Company</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div style=\"margin-bottom:3%; align-items:center;display:flex; flex-direction: column;\">\r\n");
      out.write("\t\t\t\t\t<img style=\"border-radius: 30px;width:90%;\" src=\"/resources/images/ad3.gif\"/>\r\n");
      out.write("\t\t\t\t\t<div style=\"margin-top:2%; font-size:20pt; font-weight:bold;font-style: italic;\">Kaja hire</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/hire/InsertReviewForm.jsp(9,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/resources/js/jquery-3.1.1.js");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/views/hire/InsertReviewForm.jsp(10,36) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/resources/js/jobJS.js");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /WEB-INF/views/hire/InsertReviewForm.jsp(11,36) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/resources/js/bootstrap.js");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /WEB-INF/views/hire/InsertReviewForm.jsp(12,29) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("/resources/css/bootstrap.css");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }
}
